#!bin/bash
# description : check remote hosts connectivity
# author : yousef fikry 
# email : yfi2030@gmail.com

hosts="./hostsFile"

for item in $(cat $hosts)
do
  ip=$(echo ${item} | cut -d "-" -f 1)
  name=$(echo ${item} | cut -d "-" -f 2)
  
  ping -c 1 $ip &> /dev/null
  
  if [ $? -eq 0 ]
  then 
    echo $name is OK
  else 
    echo $name is Not OK
  fi

done